name: RPGJobsAndCrafts
main: com.RPGJC.Main
version: 1.0
api-version: 1.13
softdepend: [Citizens]
commands:
  createracenpc:
    usage: /createracenpc
    description: Create a race npc
  resetrace:
    usage: /resetrace
    description: Reset your race
  menu:
    usage: /menu
    description: Open menu